# Generated by Django 4.2.8 on 2023-12-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemaddition',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
