# Generated by Django 4.2.8 on 2023-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemaddition_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemaddition',
            name='commission',
            field=models.FloatField(default=0.13),
        ),
    ]
