# Generated by Django 4.2.8 on 2023-12-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemaddition_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemaddition',
            name='commission',
            field=models.IntegerField(default=13),
        ),
    ]
