# Generated by Django 4.2.8 on 2023-12-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_itemaddition_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemaddition',
            name='commission',
            field=models.IntegerField(default=13, verbose_name='% Комиссии'),
        ),
        migrations.AlterField(
            model_name='itemaddition',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='itemaddition',
            name='price_per_item',
            field=models.FloatField(verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='itemaddition',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='itemaddition',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Купил'), ('SELL', 'Продал')], default='BUY', max_length=4, verbose_name='Тип сделки'),
        ),
    ]
