# Generated by Django 4.2.8 on 2023-12-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_image_alter_itemaddition_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemaddition',
            name='image',
        ),
        migrations.RemoveField(
            model_name='itemaddition',
            name='link',
        ),
    ]
