# Generated by Django 4.2.8 on 2023-12-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_itemaddition_image_remove_itemaddition_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemaddition',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, default='http://example.com', null=True),
        ),
    ]
