# Generated by Django 4.2.8 on 2023-12-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_options_alter_itemaddition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
