# Generated by Django 4.2.8 on 2023-12-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='itemaddition',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
