# Generated by Django 4.2.8 on 2023-12-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_options_alter_itemaddition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemaddition',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
    ]
