# Generated by Django 4.2.8 on 2023-12-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
