# Generated by Django 4.2.8 on 2023-12-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_item_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spread',
            field=models.FloatField(default=0.0),
        ),
    ]
