# Generated by Django 4.2.8 on 2023-12-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_item_spread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-last_deal_time']},
        ),
        migrations.AddField(
            model_name='item',
            name='last_deal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
