# Generated by Django 4.2.8 on 2023-12-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_item_options_item_last_deal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='target',
            field=models.FloatField(default=0.0),
        ),
    ]
