# Generated by Django 4.2.8 on 2023-12-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_item_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='target',
        ),
    ]
