# Generated by Django 4.2.8 on 2023-12-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_remove_item_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='target',
            field=models.FloatField(default=0.0),
        ),
    ]
