# Generated by Django 4.2.8 on 2023-12-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['timestamp']},
        ),
    ]
