# Generated by Django 4.2.8 on 2024-01-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_pricehistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new_current_price',
            field=models.FloatField(default=0.0),
        ),
    ]
