# Generated by Django 4.2.8 on 2024-01-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_item_new_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='new_current_price',
        ),
    ]
